@aloha_feels_loc = Location.create(country:"USA", state:"Hawaii", city:"Hakalau", street:"Old Mamalahoa highway", building_no:"29-2089", zip:"96710")
@alma_chocolate_loc = Location.create(country:"USA", state:"Oregon", city:"Portland", street:"NE 28th Avenue", building_no:"140", zip:"97232")

@amano_loc = Location.create(country:"USA", state:"Utah", city:"Orem", street:"496 South 1325 West", zip:"84058")
@askinosie_loc = Location.create(country:"USA", state:"Missouri", ciy:"Springfield", street:"E. Commercial", building_no:"65803", zip:"65803")
@beach_chocolate_factory_loc = Location.create(country:"Costa Rica", street:"Playa Brasilito", building_no:"127")
@belicious_loc = Location.create(country:"Canada", city:"Slocan", zip:"V0G2C0")
@black_mountain_chocolate_loc = Location.create(country:"USA", state:"North Carolina", city:"Winston-Salem", street:"Trade St NW", building_no:"732", zip:"27101")
@aacaoteca_loc = Location.create(country:"Dominican Republic", city:"Gazcue Santo Domingo", street:"Calle Mahatma Gandhi", building_no:"153")
@caribean_chocolate_loc = Location.create(country:"Costa Rica", city:"Puerto Viejo", street:"mets Oeste de Tasty Waves Playa Cocles", buiding_no:"25")
@castronovo_loc = Location.create(country:"USA", state:"Florida", street:"Colorado Avenue in Stuart", building_no:"555", zip:"34994")
